<?php

namespace Database\Seeders;

use App\Models\Warga;
use Illuminate\Database\Seeder;

class WargaSeeder extends Seeder
{
    public function run(): void
    {
        Warga::whereNotNull('id')->delete();

        $data = [
            ['nik' => '3273010101900001', 'kk' => '3273010101900001', 'nama' => 'Agus Supriyadi', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => '1990-01-01', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 1', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Pegawai Negeri Sipil', 'pendidikan' => 'S1', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567890', 'email' => 'agus.supriyadi@email.com', 'aktif' => true],
            ['nik' => '3273010102900002', 'kk' => '3273010101900001', 'nama' => 'Siti Nurhaliza', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => '1992-02-02', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 1', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Ibu Rumah Tangga', 'pendidikan' => 'S1', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567891', 'email' => 'siti.nurhaliza@email.com', 'aktif' => true],
            ['nik' => '3273010103900003', 'kk' => '3273010101900001', 'nama' => 'Budi Santoso', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => '1985-03-03', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 2', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Wiraswasta', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567892', 'email' => 'budi.santoso@email.com', 'aktif' => true],
            ['nik' => '3273010104900004', 'kk' => '3273010104900004', 'nama' => 'Dewi Lestari', 'tempat_lahir' => 'Surabaya', 'tanggal_lahir' => '1995-04-04', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 3', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Guru', 'pendidikan' => 'S1', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567893', 'email' => 'dewi.lestari@email.com', 'aktif' => true],
            ['nik' => '3273010105900005', 'kk' => '3273010104900004', 'nama' => 'Ahmad Fauzi', 'tempat_lahir' => 'Semarang', 'tanggal_lahir' => '1988-05-05', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 3', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Dokter', 'pendidikan' => 'Profesi', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567894', 'email' => 'ahmad.fauzi@email.com', 'aktif' => true],
            ['nik' => '3273010106900006', 'kk' => '3273010104900004', 'nama' => 'Rina Marlina', 'tempat_lahir' => 'Yogyakarta', 'tanggal_lahir' => '1990-06-06', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 3', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Perawat', 'pendidikan' => 'D3', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567895', 'email' => 'rina.marlina@email.com', 'aktif' => true],
            ['nik' => '3273010107900007', 'kk' => '3273010107900007', 'nama' => 'Hendra Gunawan', 'tempat_lahir' => 'Medan', 'tanggal_lahir' => '1982-07-07', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 4', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Kristen', 'pekerjaan' => 'Pengacara', 'pendidikan' => 'S2', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567896', 'email' => 'hendra.gunawan@email.com', 'aktif' => true],
            ['nik' => '3273010108900008', 'kk' => '3273010107900007', 'nama' => 'Maria Simanjuntak', 'tempat_lahir' => 'Medan', 'tanggal_lahir' => '1985-08-08', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 4', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Kristen', 'pekerjaan' => 'Dosen', 'pendidikan' => 'S2', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567897', 'email' => 'maria.simanjuntak@email.com', 'aktif' => true],
            ['nik' => '3273010109900009', 'kk' => '3273010109900009', 'nama' => 'Eko Prasetyo', 'tempat_lahir' => 'Malang', 'tanggal_lahir' => '1993-09-09', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 5', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Programmer', 'pendidikan' => 'S1', 'status_warga' => 'kontrakan', 'status_keluarga' => 'kepala', 'telepon' => '081234567898', 'email' => 'eko.prasetyo@email.com', 'aktif' => true],
            ['nik' => '3273010110900010', 'kk' => '3273010110900010', 'nama' => 'Fitri Handayani', 'tempat_lahir' => 'Bogor', 'tanggal_lahir' => '1991-10-10', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 6', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Akuntan', 'pendidikan' => 'S1', 'status_warga' => 'kontrakan', 'status_keluarga' => 'kepala', 'telepon' => '081234567899', 'email' => 'fitri.handayani@email.com', 'aktif' => true],
            ['nik' => '3273010111900011', 'kk' => '3273010110900010', 'nama' => 'Rizky Pratama', 'tempat_lahir' => 'Depok', 'tanggal_lahir' => '2015-11-11', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 6', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Pelajar', 'pendidikan' => 'SD', 'status_warga' => 'kontrakan', 'status_keluarga' => 'anak', 'telepon' => '081234567800', 'email' => null, 'aktif' => true],
            ['nik' => '3273010112900012', 'kk' => '3273010112900012', 'nama' => 'Doni Lesmana', 'tempat_lahir' => 'Tangerang', 'tanggal_lahir' => '1987-12-12', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 7', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Supir', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567801', 'email' => 'doni.lesmana@email.com', 'aktif' => true],
            ['nik' => '3273010113900013', 'kk' => '3273010112900012', 'nama' => 'Rina Amelia', 'tempat_lahir' => 'Bekasi', 'tanggal_lahir' => '1990-01-13', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 7', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Penjahit', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567802', 'email' => 'rina.amelia@email.com', 'aktif' => true],
            ['nik' => '3273010114900014', 'kk' => '3273010114900014', 'nama' => 'Yusuf Rahman', 'tempat_lahir' => 'Cirebon', 'tanggal_lahir' => '1983-02-14', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 8', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Pedagang', 'pendidikan' => 'SMP', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567803', 'email' => 'yusuf.rahman@email.com', 'aktif' => true],
            ['nik' => '3273010115900015', 'kk' => '3273010114900014', 'nama' => 'Siti Fatimah', 'tempat_lahir' => 'Cirebon', 'tanggal_lahir' => '1986-03-15', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 8', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Ibu Rumah Tangga', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567804', 'email' => null, 'aktif' => true],
            ['nik' => '3273010116900016', 'kk' => '3273010116900016', 'nama' => 'Herman Susilo', 'tempat_lahir' => 'Purwokerto', 'tanggal_lahir' => '1978-04-16', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 9', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Petani', 'pendidikan' => 'SMP', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567805', 'email' => null, 'aktif' => true],
            ['nik' => '3273010117900017', 'kk' => '3273010116900016', 'nama' => 'Sri Wahyuni', 'tempat_lahir' => 'Purwokerto', 'tanggal_lahir' => '1981-05-17', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 9', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Buruh', 'pendidikan' => 'SMP', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567806', 'email' => null, 'aktif' => true],
            ['nik' => '3273010118900018', 'kk' => '3273010118900018', 'nama' => 'Bayu Aji', 'tempat_lahir' => 'Solo', 'tanggal_lahir' => '1996-06-18', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 10', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Mahasiswa', 'pendidikan' => 'S1', 'status_warga' => 'kos', 'status_keluarga' => 'lainnya', 'telepon' => '081234567807', 'email' => 'bayu.aji@email.com', 'aktif' => true],
            ['nik' => '3273010119900019', 'kk' => '3273010119900019', 'nama' => 'Mega Putri', 'tempat_lahir' => 'Bali', 'tanggal_lahir' => '1997-07-19', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 11', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Hindu', 'pekerjaan' => 'Mahasiswa', 'pendidikan' => 'S1', 'status_warga' => 'kos', 'status_keluarga' => 'lainnya', 'telepon' => '081234567808', 'email' => 'mega.putri@email.com', 'aktif' => true],
            ['nik' => '3273010120900020', 'kk' => '3273010120900020', 'nama' => 'Andi Wijaya', 'tempat_lahir' => 'Makassar', 'tanggal_lahir' => '1989-08-20', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 12', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Karyawan Swasta', 'pendidikan' => 'S1', 'status_warga' => 'kontrakan', 'status_keluarga' => 'kepala', 'telepon' => '081234567809', 'email' => 'andi.wijaya@email.com', 'aktif' => true],
            ['nik' => '3273010121900021', 'kk' => '3273010120900020', 'nama' => 'Citra Ayu', 'tempat_lahir' => 'Makassar', 'tanggal_lahir' => '1992-09-21', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 12', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Desainer', 'pendidikan' => 'S1', 'status_warga' => 'kontrakan', 'status_keluarga' => 'istri', 'telepon' => '081234567810', 'email' => 'citra.ayu@email.com', 'aktif' => true],
            ['nik' => '3273010122900022', 'kk' => '3273010122900022', 'nama' => 'Deni Nugroho', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => '1994-10-22', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 13', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Fotografer', 'pendidikan' => 'D3', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567811', 'email' => 'deni.nugroho@email.com', 'aktif' => true],
            ['nik' => '3273010123900023', 'kk' => '3273010122900022', 'nama' => 'Elsa Safitri', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => '1996-11-23', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 13', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Pramugari', 'pendidikan' => 'D3', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567812', 'email' => 'elsa.safitri@email.com', 'aktif' => true],
            ['nik' => '3273010124900024', 'kk' => '3273010124900024', 'nama' => 'Fajar Hidayat', 'tempat_lahir' => 'Lampung', 'tanggal_lahir' => '1986-12-24', 'jenis_kelamin' => 'L', 'alamat' => 'Jl. Merdeka No. 14', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Satpam', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'kepala', 'telepon' => '081234567813', 'email' => null, 'aktif' => true],
            ['nik' => '3273010125900025', 'kk' => '3273010124900024', 'nama' => 'Gita Puspita', 'tempat_lahir' => 'Lampung', 'tanggal_lahir' => '1990-01-25', 'jenis_kelamin' => 'P', 'alamat' => 'Jl. Merdeka No. 14', 'rt' => '01', 'rw' => '01', 'kelurahan' => 'Kelurahan Contoh', 'kecamatan' => 'Kecamatan Contoh', 'kota' => 'Kota Contoh', 'provinsi' => 'Provinsi Contoh', 'agama' => 'Islam', 'pekerjaan' => 'Pedagang', 'pendidikan' => 'SMA', 'status_warga' => 'tetap', 'status_keluarga' => 'istri', 'telepon' => '081234567814', 'email' => null, 'aktif' => true],
        ];

        foreach ($data as $item) {
            Warga::create($item);
        }
    }
}
